"""initial_schema

Revision ID: 7bc787ffc064
Revises: 
Create Date: 2026-09-13 12:43:11.017641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc787ffc064'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standards',
    sa.Column('grade_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standards_grade_number'), ['grade_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_standards_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('standard_id', sa.String(length=36), nullable=True),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.Column('enrollment_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_enrollment_number'), ['enrollment_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_standard_id'), ['standard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('subjects',
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standard_id', 'code', name='uq_subject_standard_code')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_standard_id'), ['standard_id'], unique=False)

    op.create_table('teacher_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_profiles_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('chapters',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'chapter_number', name='uq_chapter_subject_order')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_subject_id'), ['subject_id'], unique=False)

    op.create_table('topics',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('topic_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_objectives', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'topic_order', name='uq_topic_chapter_order')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_id'), ['id'], unique=False)

    op.create_table('assessments',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'COMPLETED', 'ARCHIVED', name='assessmentstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_topic_id'), ['topic_id'], unique=False)

    op.create_table('forgetting_signals',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('prior_performance_ref', sa.JSON(), nullable=True),
    sa.Column('later_performance_ref', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('UNRESOLVED', 'ADDRESSED_BY_REVISION', 'DISMISSED', name='forgettingsignalstatus'), nullable=False),
    sa.Column('confidence_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forgetting_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forgetting_signals_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forgetting_signals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forgetting_signals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_forgetting_signals_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forgetting_signals_topic_id'), ['topic_id'], unique=False)

    op.create_table('learning_contents',
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'EXAMPLE', 'DEFINITION', 'FORMULA', 'EXPLANATION', 'QUESTION_REFERENCE', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('chunk_identifier', sa.String(length=100), nullable=True),
    sa.Column('content_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_contents_chunk_identifier'), ['chunk_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_contents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_contents_source_document'), ['source_document'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_contents_topic_id'), ['topic_id'], unique=False)

    op.create_table('revision_plans',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_revision_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='revisionpriority'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('completion_state', sa.Enum('PENDING', 'COMPLETED', 'DISMISSED', 'OVERDUE', name='revisioncompletionstate'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revision_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_plans_completion_state'), ['completion_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_plans_recommended_revision_at'), ['recommended_revision_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_plans_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_plans_topic_id'), ['topic_id'], unique=False)

    op.create_table('teacher_actions',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.Enum('RECOMMEND_REVISION', 'ASSIGN_PRACTICE', 'FLAG_TOPIC', 'REVIEW_PERFORMANCE', name='teacheractiontype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_actions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_actions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_actions_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_actions_topic_id'), ['topic_id'], unique=False)

    op.create_table('topic_performances',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('practice_count', sa.Integer(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=False),
    sa.Column('hint_usage_count', sa.Integer(), nullable=False),
    sa.Column('mastery_state', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'topic_id', name='uq_student_topic_performance')
    )
    with op.batch_alter_table('topic_performances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_performances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_performances_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_performances_topic_id'), ['topic_id'], unique=False)

    op.create_table('attempts',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'SUBMITTED', 'ABANDONED', name='attemptstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_student_id'), ['student_id'], unique=False)

    op.create_table('mcq_questions',
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('correct_option', sa.Enum('A', 'B', 'C', 'D', name='optionkey'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='questiondifficulty'), nullable=False),
    sa.Column('source_content_id', sa.String(length=36), nullable=True),
    sa.Column('generation_model', sa.String(length=100), nullable=True),
    sa.Column('generation_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED', 'ARCHIVED', name='questionstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_content_id'], ['learning_contents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcq_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcq_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcq_questions_source_content_id'), ['source_content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcq_questions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcq_questions_topic_id'), ['topic_id'], unique=False)

    op.create_table('answers',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option', sa.Enum('A', 'B', 'C', 'D', name='optionkey'), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['mcq_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_question_answer')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_question_id'), ['question_id'], unique=False)

    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['mcq_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'question_id', name='uq_assessment_question')
    )
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_questions_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_questions_question_id'), ['question_id'], unique=False)

    op.create_table('learning_events',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('LEARN', 'PRACTICE', 'MCQ_ATTEMPT', 'REVISION', 'REVIEW', name='eventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('correctness', sa.Boolean(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_events_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_events_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_learning_events_student_timestamp', ['student_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_learning_events_student_topic', ['student_id', 'topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_events_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index('ix_learning_events_topic_timestamp', ['topic_id', 'timestamp'], unique=False)

    op.create_table('question_history',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('normalized_question_text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_reference', sa.String(length=255), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['mcq_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_history_question_id'), ['question_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_question_history_text_hash'), ['text_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_history_text_hash'))
        batch_op.drop_index(batch_op.f('ix_question_history_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_history_id'))

    op.drop_table('question_history')
    with op.batch_alter_table('learning_events', schema=None) as batch_op:
        batch_op.drop_index('ix_learning_events_topic_timestamp')
        batch_op.drop_index(batch_op.f('ix_learning_events_topic_id'))
        batch_op.drop_index(batch_op.f('ix_learning_events_timestamp'))
        batch_op.drop_index('ix_learning_events_student_topic')
        batch_op.drop_index('ix_learning_events_student_timestamp')
        batch_op.drop_index(batch_op.f('ix_learning_events_student_id'))
        batch_op.drop_index(batch_op.f('ix_learning_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_learning_events_id'))
        batch_op.drop_index(batch_op.f('ix_learning_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_learning_events_attempt_id'))

    op.drop_table('learning_events')
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_questions_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_questions_assessment_id'))

    op.drop_table('assessment_questions')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_answers_id'))
        batch_op.drop_index(batch_op.f('ix_answers_attempt_id'))

    op.drop_table('answers')
    with op.batch_alter_table('mcq_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcq_questions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_mcq_questions_status'))
        batch_op.drop_index(batch_op.f('ix_mcq_questions_source_content_id'))
        batch_op.drop_index(batch_op.f('ix_mcq_questions_id'))

    op.drop_table('mcq_questions')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_attempts_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_assessment_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('topic_performances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_performances_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_performances_student_id'))
        batch_op.drop_index(batch_op.f('ix_topic_performances_id'))

    op.drop_table('topic_performances')
    with op.batch_alter_table('teacher_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_actions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_actions_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_actions_student_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_actions_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_actions_action_type'))

    op.drop_table('teacher_actions')
    with op.batch_alter_table('revision_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_plans_topic_id'))
        batch_op.drop_index(batch_op.f('ix_revision_plans_student_id'))
        batch_op.drop_index(batch_op.f('ix_revision_plans_recommended_revision_at'))
        batch_op.drop_index(batch_op.f('ix_revision_plans_id'))
        batch_op.drop_index(batch_op.f('ix_revision_plans_completion_state'))

    op.drop_table('revision_plans')
    with op.batch_alter_table('learning_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_contents_topic_id'))
        batch_op.drop_index(batch_op.f('ix_learning_contents_source_document'))
        batch_op.drop_index(batch_op.f('ix_learning_contents_id'))
        batch_op.drop_index(batch_op.f('ix_learning_contents_chunk_identifier'))

    op.drop_table('learning_contents')
    with op.batch_alter_table('forgetting_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forgetting_signals_topic_id'))
        batch_op.drop_index(batch_op.f('ix_forgetting_signals_student_id'))
        batch_op.drop_index(batch_op.f('ix_forgetting_signals_status'))
        batch_op.drop_index(batch_op.f('ix_forgetting_signals_id'))
        batch_op.drop_index(batch_op.f('ix_forgetting_signals_detected_at'))

    op.drop_table('forgetting_signals')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_topic_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_status'))
        batch_op.drop_index(batch_op.f('ix_assessments_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_id'))
        batch_op.drop_index(batch_op.f('ix_topics_chapter_id'))

    op.drop_table('topics')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_subject_id'))
        batch_op.drop_index(batch_op.f('ix_chapters_id'))

    op.drop_table('chapters')
    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_profiles_employee_id'))

    op.drop_table('teacher_profiles')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_standard_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_code'))

    op.drop_table('subjects')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_standard_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_enrollment_number'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('standards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standards_id'))
        batch_op.drop_index(batch_op.f('ix_standards_grade_number'))

    op.drop_table('standards')
    # ### end Alembic commands ###
