"""strengthen_constraints_and_forgetting_signal

Revision ID: e025394444f5
Revises: 7bc787ffc064
Create Date: 2026-09-13 12:53:41.274098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e025394444f5'
down_revision: Union[str, None] = '7bc787ffc064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forgetting_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_strength', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prior_performance_reference', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('later_performance_reference', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('evidence_metadata', sa.JSON(), nullable=True))
        batch_op.drop_column('later_performance_ref')
        batch_op.drop_column('prior_performance_ref')
        batch_op.drop_column('confidence_metadata')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')

    with op.batch_alter_table('forgetting_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_metadata', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('prior_performance_ref', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('later_performance_ref', sqlite.JSON(), nullable=True))
        batch_op.drop_column('evidence_metadata')
        batch_op.drop_column('later_performance_reference')
        batch_op.drop_column('prior_performance_reference')
        batch_op.drop_column('evidence_strength')

    # ### end Alembic commands ###
