# Curriculum Constants
SUPPORTED_STANDARDS = [9, 10, 11, 12]

# Application-Facing Mastery States (Evidence Aggregation heuristics, NOT ML retention scores)
MASTERY_STATE_UNASSESSED = "UNASSESSED"
MASTERY_STATE_NOVICE = "NOVICE"
MASTERY_STATE_PRACTICING = "PRACTICING"
MASTERY_STATE_MASTERED = "MASTERED"

VALID_MASTERY_STATES = {
    MASTERY_STATE_UNASSESSED,
    MASTERY_STATE_NOVICE,
    MASTERY_STATE_PRACTICING,
    MASTERY_STATE_MASTERED,
}

# Evidence Strength Levels for ForgettingSignal (Categorical qualitative evidence, NOT a probability)
EVIDENCE_STRENGTH_WEAK = "WEAK"
EVIDENCE_STRENGTH_MODERATE = "MODERATE"
EVIDENCE_STRENGTH_STRONG = "STRONG"

VALID_EVIDENCE_STRENGTHS = {
    EVIDENCE_STRENGTH_WEAK,
    EVIDENCE_STRENGTH_MODERATE,
    EVIDENCE_STRENGTH_STRONG,
}

# API Constants
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 200
